# Use official Node.js image as a base
FROM node:16-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from the backend directory
COPY package.json package-lock.json ./

# Install backend dependencies
RUN npm install

# Copy all backend files into the container
COPY . .

# Expose port 5000 for the backend server
EXPOSE 5000

# Start the Express server
CMD ["node", "index.js"]
